set_property PACKAGE_PIN U9 [get_ports b[0]]
set_property IOSTANDARD LVCMOS33 [get_ports b[0]]
set_property PACKAGE_PIN U8 [get_ports b[1]]
set_property IOSTANDARD LVCMOS33 [get_ports b[1]]
set_property PACKAGE_PIN R7 [get_ports b[2]]
set_property IOSTANDARD LVCMOS33 [get_ports b[2]]
set_property PACKAGE_PIN R6 [get_ports b[3]]
set_property IOSTANDARD LVCMOS33 [get_ports b[3]]

set_property PACKAGE_PIN R5 [get_ports a[0]]
set_property IOSTANDARD LVCMOS33 [get_ports a[0]]
set_property PACKAGE_PIN V7 [get_ports a[1]]
set_property IOSTANDARD LVCMOS33 [get_ports a[1]]
set_property PACKAGE_PIN V6 [get_ports a[2]]
set_property IOSTANDARD LVCMOS33 [get_ports a[2]]
set_property PACKAGE_PIN V5 [get_ports a[3]]
set_property IOSTANDARD LVCMOS33 [get_ports a[3]]

set_property PACKAGE_PIN P4 [get_ports cin]
set_property IOSTANDARD LVCMOS33 [get_ports cin]

set_property PACKAGE_PIN T8 [get_ports s[0]]
set_property IOSTANDARD LVCMOS33 [get_ports s[0]]
set_property PACKAGE_PIN V9 [get_ports s[1]]
set_property IOSTANDARD LVCMOS33 [get_ports s[1]]
set_property PACKAGE_PIN R8 [get_ports s[2]]
set_property IOSTANDARD LVCMOS33 [get_ports s[2]]
set_property PACKAGE_PIN T6 [get_ports s[3]]
set_property IOSTANDARD LVCMOS33 [get_ports s[3]]

set_property PACKAGE_PIN P2 [get_ports cout]
set_property IOSTANDARD LVCMOS33 [get_ports cout]
