set_property PACKAGE_PIN U9 [get_ports b[0]]
set_property IOSTANDARD LVCMOS33 [get_ports b[0]]
set_property PACKAGE_PIN U8 [get_ports b[1]]
set_property IOSTANDARD LVCMOS33 [get_ports b[1]]
set_property PACKAGE_PIN R7 [get_ports a[0]]
set_property IOSTANDARD LVCMOS33 [get_ports a[0]]
set_property PACKAGE_PIN R6 [get_ports a[1]]
set_property IOSTANDARD LVCMOS33 [get_ports a[1]]

set_property PACKAGE_PIN T8 [get_ports product[0]]
set_property IOSTANDARD LVCMOS33 [get_ports product[0]]
set_property PACKAGE_PIN V9 [get_ports product[1]]
set_property IOSTANDARD LVCMOS33 [get_ports product[1]]
set_property PACKAGE_PIN R8 [get_ports product[2]]
set_property IOSTANDARD LVCMOS33 [get_ports product[2]]
set_property PACKAGE_PIN T6 [get_ports product[3]]
set_property IOSTANDARD LVCMOS33 [get_ports product[3]]
