set_property PACKAGE_PIN U9 [get_ports x[0]]
set_property IOSTANDARD LVCMOS33 [get_ports x[0]]
set_property PACKAGE_PIN U8 [get_ports x[1]]
set_property IOSTANDARD LVCMOS33 [get_ports x[1]]
set_property PACKAGE_PIN R7 [get_ports x[2]]
set_property IOSTANDARD LVCMOS33 [get_ports x[2]]

set_property PACKAGE_PIN T8 [get_ports y[0]]
set_property IOSTANDARD LVCMOS33 [get_ports y[0]]
set_property PACKAGE_PIN V9 [get_ports y[1]]
set_property IOSTANDARD LVCMOS33 [get_ports y[1]]
set_property PACKAGE_PIN R8 [get_ports y[2]]
set_property IOSTANDARD LVCMOS33 [get_ports y[2]]
set_property PACKAGE_PIN T6 [get_ports y[3]]
set_property IOSTANDARD LVCMOS33 [get_ports y[3]]
set_property PACKAGE_PIN T5 [get_ports y[4]]
set_property IOSTANDARD LVCMOS33 [get_ports y[4]]
set_property PACKAGE_PIN T4 [get_ports y[5]]
set_property IOSTANDARD LVCMOS33 [get_ports y[5]]
set_property PACKAGE_PIN U7 [get_ports y[6]]
set_property IOSTANDARD LVCMOS33 [get_ports y[6]]
set_property PACKAGE_PIN U6 [get_ports y[7]]
set_property IOSTANDARD LVCMOS33 [get_ports y[7]]

